# .github/workflows/fetch.yml
name: Fetch OHLC and publish

on:
  schedule:
    - cron: "*/5 * * * *"   # elke 5 minuten
  workflow_dispatch:        # handmatig starten kan ook

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: pip install requests

      - name: Fetch & build latest.json
        run: python fetch_and_publish.py

      - name: Commit & push changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add latest.json ohlc_data/*.csv || true
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "update: ${{ github.run_id }}"
            git push
          fi
