name: Fetch OHLC and publish (OKX Perp → main)

on:
  schedule:
    - cron: "*/5 * * * *"   # elke 5 min (pas aan naar wens)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build latest.json (perp 1m+15m)
        env:
          LIMIT: 200
        run: python fetch_and_publish.py

      - name: Commit & push
        run: |
          git config user.name "gh-actions"
          git config user.email "actions@github.com"
          git add data/latest.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "auto: refresh data/latest.json (perp 1m+15m) [skip ci]"
            git push origin HEAD:main
