name: Fetch OHLC and publish

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/10 * * * *"   # elke 10 minuten (pas aan naar wens)

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch & build latest.json
        run: |
          python fetch_and_publish.py

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/latest.json
          if git diff --cached --quiet; then
            echo "No data changes to commit."
          else
            git commit -m "data: update latest.json ($(date -u +%F' '%T) UTC)"
            git push
          fi
