name: Fetch OHLC and publish (OKX → main)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"   # elke 5 minuten (pas aan wat je wilt)

permissions:
  contents: write   # nodig om direct naar main te pushen

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true   # gebruik GITHUB_TOKEN om te pushen

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch & build latest.json (OKX)
        run: |
          python fetch_and_publish.py --exchange okx --interval 1m --limit 200

      - name: Commit & push to main
        run: |
          git config user.name "gh-actions"
          git config user.email "actions@github.com"
          git add data/latest.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "auto: refresh data/latest.json [skip ci]"
            git push origin HEAD:main
          fi
