name: Fetch OHLC and publish (OKX Perp → main)

on:
  schedule:
    - cron: "*/5 * * * *"   # elke 5 minuten automatisch runnen
  workflow_dispatch:        # handmatig runnen blijft ook mogelijk

permissions:
  contents: write           # nodig om naar main te pushen

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch & build latest.json (OKX Perp)
        env:
          BAR: 1m
          LIMIT: 200
        run: python fetch_and_publish.py

      - name: Commit & push changes
        run: |
          git config user.name "gh-actions"
          git config user.email "actions@github.com"
          git add data/latest.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "auto: refresh data/latest.json (perp) [skip ci]"
            git push origin HEAD:main
          fi
