name: Snapshot - MEXC Perps

on:
  schedule:
    - cron: "*/20 * * * *"  # elke 20 min
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install ccxt

      - name: Run snapshot
        run: python scripts/mexc_snapshot.py

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "snapshot-bot"
            git config user.email "actions@github.com"
            git add data/summary.json SNAPSHOT.md
            git commit -m "update snapshot $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes."
          fi
