name: Snapshot (MEXC Perp)

on:
  schedule:
    - cron: "*/10 * * * *"   # elke 10 minuten (UTC)
  workflow_dispatch: {}       # handmatig starten

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run snapshot script
        run: python scripts/snapshot.py

      - name: Commit snapshot
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # >>> Belangrijk: ALLES toevoegen (data/ én SNAPSHOT.md)
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update snapshot: $(date -u +'%Y-%m-%dT%H:%M:%SZ') [skip ci]"
            git push
          fi
