name: Refresh Snapshot

on:
  schedule:
    - cron: "*/10 * * * *"   # elke 10 minuten (UTC)
  workflow_dispatch:         # handmatig starten in GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run snapshot script
        run: |
          python scripts/snapshot.py

      - name: Commit snapshot
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/summary.json
          git commit -m "Update snapshot [skip ci]" || echo "No changes"
          git push
